export const ADD_GOAL = "ADD_GOAL";
export const EDIT_GOAL = "EDIT_GOAL";
export const DELETE_GOAL = "DELETE_GOAL";
export const MARK_GOAL = "MARK_GOAL";
export const DELETE_ALL_GOALS = "DELETE_ALL_GOALS";
export const CLEAR_COMPLETED_GOALS = "CLEAR_COMPLETED_GOALS";

export const TOGGLE_SHOW_COMPLETED = "TOGGLE_SHOW_COMPLETED"